from economy import Economy
economy = Economy(id = "EXTREME",
                  numeric_id = 2,
                  # as of May 2015 the following cargos must have fixed positions if used by an economy:
                  # passengers: 0, mail: 2, goods 5, food 11
                  # keep the rest of the cargos alphabetised
                  # bump the min. compatible version if this list changes
                  cargos = ['passengers',
                            'alcohol',
                            'mail',
                            'ammonia',
                            'bauxite',
                            'goods',
                            'building_materials',
                            'cement',
                            'chlorine',
                            'clay',
                            'coal',
                            'food',
                            'engineering_supplies',
                            'ethylene',
                            'farm_supplies',
                            'fish',
                            'fruits',
                            'grain',
                            'iron_ore',
                            'livestock',
                            'limestone',
                            'lumber',
                            'packaging',
                            'milk',
                            'oil',
                            'petrol',
                            'phosphate',
                            'plant_fibres',
                            'potash',
                            'recyclables',
                            'salt',
                            'sand',
                            'scrap_metal',
                            'soda_ash',
                            'steel',
                            'sulphur',
                            'sugar_beet',
                            'wood',
                            'wool'])
