from cargo import Cargo

cargo = Cargo(id='adhesives',
              type_name='string(STR_CARGO_NAME_ADHESIVES)',
              unit_name='string(STR_CARGO_NAME_ADHESIVES)',
              type_abbreviation='string(STR_CID_ADHESIVES)',
              sprite='NEW_CARGO_SPRITE',
              weight='0.65',
              cargo_payment_list_colour='145',
              is_freight='1',
              cargo_classes='bitmask(CC_PIECE_GOODS, CC_LIQUID)',
              cargo_label='GLUE',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_LITERS',
              items_of_cargo='string(STR_CARGO_UNIT_ADHESIVES)',
              penalty_lowerbound='16',
              single_penalty_length='120',
              price_factor='127',
              capacity_multiplier='1',
              icon_indices=(7, 1))
