from cargo import Cargo

cargo = Cargo(id='cotton',
              type_name='string(STR_CARGO_NAME_COTTON)',
              unit_name='string(STR_CARGO_NAME_COTTON)',
              type_abbreviation='string(STR_CID_COTTON)',
              sprite='NEW_CARGO_SPRITE',
              weight='0.2',
              cargo_payment_list_colour='12',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK, CC_PIECE_GOODS)',
              cargo_label='COTT',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='TTD_STR_TONS',
              items_of_cargo='string(STR_CARGO_UNIT_COTTON)',
              penalty_lowerbound='10',
              single_penalty_length='36',
              capacity_multiplier='1',
              price_factor='107',
              icon_indices=(3, 1))
