from cargo import Cargo

cargo = Cargo(id='detergents',
              type_name='string(STR_CARGO_NAME_DETERGENTS)',
              unit_name='string(STR_CARGO_NAME_DETERGENTS)',
              type_abbreviation='string(STR_CID_DETERGENTS)',
              sprite='NEW_CARGO_SPRITE',
              weight='1.0',
              cargo_payment_list_colour='187',
              is_freight='1',
              cargo_classes='bitmask(CC_BULK, CC_COVERED)',
              cargo_label='SOAP',
              town_growth_effect='TOWNGROWTH_NONE',
              town_growth_multiplier='1.0',
              units_of_cargo='82',
              items_of_cargo='string(STR_CARGO_UNIT_DETERGENTS)',
              penalty_lowerbound='12',
              single_penalty_length='255',
              price_factor='82',
              capacity_multiplier='1',
              icon_indices=(12, 3))
